replace flask with django
SkoltechSummerCamp/5Gst pull request #14
Opened 2022-07-12 11:50 UTC by iStrannik

2022-07-12 19:00 UTC, AdvancerMan requested changes
Все ок, из критического только [захардкоженный адрес в сваггер клиенте](https://github.com/SkoltechSummerCamp/5Gst/pull/14#discussion_r919308166). Остальное можно сделать после мерджа, чтобы не блокировать остальных

2022-07-13 08:58 UTC, iStrannik commented on service/iperf_wrapper.py
>      env_data['CONNECTING_TIMEOUT'] = os.getenv('CONNECTING_TIMEOUT', '30')
То есть ты предлагаешь убрать заменить везде переменные среды на константы в файле settings.py?

2022-07-13 09:15 UTC, iStrannik commented on service/apps/apps.py
> +            print(f'{key}: {value}')
Все принты переписать через logger?

2022-07-13 09:22 UTC, AdvancerMan commented
В settings.py будет что-то вроде PORT = os.environ['PORT']. И потом ты используешь это константу вместо env_data

2022-07-13 09:25 UTC, iStrannik commented
> В settings.py будет что-то вроде PORT = os.environ['PORT']. И потом ты используешь это константу вместо env_data

А зачем на прослойка в виде переменных среды? Почему сразу не написать PORT = 1234?

2022-07-13 09:33 UTC, AdvancerMan commented
> > В settings.py будет что-то вроде PORT = os.environ['PORT']. И потом ты используешь это константу вместо env_data
> 
> А зачем на прослойка в виде переменных среды? Почему сразу не написать PORT = 1234?

У тебя может быть разный environment (от того и название 'environment variables'), например, разные сервера - на них разные service address

2022-07-13 09:34 UTC, AdvancerMan commented on service/apps/apps.py
> +            print(f'{key}: {value}')
Ага, так будет проще логи настроить

2022-07-13 09:34 UTC, AdvancerMan commented on service/apps/apps.py
> +            print(f'{key}: {value}')
Например, можно отключить какой-то уровень логгирования/переключить логи в файл

2022-07-13 10:38 UTC, iStrannik commented on service/apps/apps.py
> +                                                     port_iperf=int(balancer_communicator.env_data['IPERF_PORT']))
Кажется эти параметры в функции вообще не нужны

2022-07-13 11:30 UTC, iStrannik commented on service/apps/models.py
> +    pass
План был в будущем, например, хранить историю запросов с ip телефонов. Пока удалил

2022-07-13 11:31 UTC, iStrannik commented on service/apps/apps.py
> +        def TimeoutHandler():
Поменял, но вообще это был старый код)

2022-07-13 11:32 UTC, iStrannik commented on service/service/settings.py
> +}
Вроде живёт

2022-07-13 11:32 UTC, iStrannik commented on service/apps/apps.py
> +            print(f'{key}: {value}')
Можно добавить в задачу на борде

2022-07-13 11:46 UTC, AdvancerMan requested changes

2022-07-13 11:46 UTC, AdvancerMan commented on service/balancer_communicator.py
Конфигурацию можно передать в конструктор, так будет лучше, так как потенциально в конструкторе она может использоваться в какой-то нетривиальной логике

2022-07-13 11:46 UTC, AdvancerMan commented on service/balancer_communicator.py
И мб лучше адрес балансера полностью в енв положить а не частями?

2022-07-13 11:46 UTC, AdvancerMan commented on service/balancer_communicator.py
>          }
Когда я говорил про константы в settings, я имел в виду отказаться полностью от env_data и использовать settings

2022-07-13 12:01 UTC, iStrannik commented on service/balancer_communicator.py
Я так сделал для удобства использования: base_url вообще можно считать, что не меняется, поэтому будет использоваться дефолтное значение, а адрес меняется постоянно. В общем лишний раз копировать base_url не хочется

2022-07-13 12:17 UTC, merged