added docker-compose file
SkoltechSummerCamp/5Gst pull request #31
Opened 2022-07-17 17:17 UTC by AndyForWork

set DEBUG,SUPPORT_EMAIL, YOURE_IP, SECRET_KEY variables

run docker compose:
docker compose up -d

this will start balancer and service on you're device

2022-07-18 10:04 UTC, AdvancerMan requested changes

2022-07-18 10:04 UTC, AdvancerMan commented on docker-compose.yml
> +    image: postgres:latest
Лучше указать последнюю версию вместо latest. Иначе есть шанс, что на новой постгре балансер перестанет работать

2022-07-18 10:04 UTC, AdvancerMan commented on docker-compose.yml
> +       sleep 60;
У тебя стоит depends_on: postgres, слип не нужен.

2022-07-18 10:04 UTC, AdvancerMan commented on docker-compose.yml
> +      "
Это все (кроме migrate) делает докерфайл балансера. Добавь migrate в докерфайл балансера и удали command отсюда.

2022-07-18 10:04 UTC, AdvancerMan commented on docker-compose.yml
> +       sleep 100;
Вместо слипа сделай healthcheck у балансера и depends_on: balancer у сервиса

2022-07-18 10:04 UTC, AdvancerMan commented on docker-compose.yml
> +      "
Это все делает докерфайл сервиса

2022-07-18 10:04 UTC, AdvancerMan commented on docker-compose.yml
> +      - "5432:5432"
Много чего еще можно вытащить в енв, чтобы запускающий сам настираивал. Пароли, порты, версии балансера/сервиса - все это можно вынести в енв

2022-07-18 10:04 UTC, AdvancerMan commented on docker-compose.yml
> +      - "5432:5432"
Для упрощения настройки можно добавить [дефолтные значения](https://docs.docker.com/compose/environment-variables/) этим константам из енва

2022-07-18 10:06 UTC, AdvancerMan commented on docker-compose.yml
> +      "
`command: ` надо убрать

2022-07-18 15:12 UTC, AndyForWork commented on docker-compose.yml
> +      "
так а разве тогда не будет бд перезаписываться каждый раз, как только запускается новый балансер (даже если балансер хочет обращаться к бд на другом серве) ?

2022-07-18 15:56 UTC, AdvancerMan requested changes

2022-07-18 15:56 UTC, AdvancerMan commented on balancer/services/views.py
> +class TestDB:
Скорее не TestDB, а PingView

2022-07-18 15:56 UTC, AdvancerMan commented on balancer/services/views.py
> +class TestDB:
отнаследуй от APIView, тогда в urls.py можно будет написать views.TestDB.as_view(), а @api_view можно будет убрать

2022-07-18 15:56 UTC, AdvancerMan commented on balancer/services/urls.py
> +from django.urls import path, include
include не используется, убери импорт

2022-07-18 16:06 UTC, AdvancerMan commented on docker-compose.yml
> +      "
Продублирую ответ сюда: бд не перезаписывается. Миграции - это применение SQL скриптов к базе. Обычно ты не делаешь миграцию `DROP DATABASE db_name`. Имена уже примененных скриптов записываются в табличке `django_migrations`, поэтому несколько раз они не применяются

2022-07-18 16:31 UTC, AdvancerMan requested changes

2022-07-18 16:31 UTC, AdvancerMan commented on balancer/services/views.py
> +    def is_running(request):
метод должен называться так же как и HTTP метод (то есть get)

2022-07-18 16:31 UTC, AdvancerMan commented on balancer/services/urls.py
> +    path('ping/',views.PingView.is_running),
.as_view()

2022-07-18 16:31 UTC, AdvancerMan commented on docker-compose.yml
> +        test: [ "CMD",  "curl", "-f", "curl http://10.16.160.104:8080/Skoltech_OpenRAN_5G/iperf_load_balancer/0.1.0/ping/"]
Хост странный

2022-07-18 16:31 UTC, AdvancerMan commented on docker-compose.yml
> +        test: [ "CMD",  "curl", "-f", "curl http://10.16.160.104:8080/Skoltech_OpenRAN_5G/iperf_load_balancer/0.1.0/ping/"]
И команда странная - как будто курл 2 раза. Мб второй курл не нужен?

2022-07-19 10:20 UTC, AdvancerMan approved these changes

2022-07-19 10:21 UTC, merged