Develop
SkoltechSummerCamp/5Gst pull request #63
Opened 2022-07-26 12:42 UTC by AndyForWork

https://github.com/SkoltechSummerCamp/5Gst/issues/34

2022-07-26 13:23 UTC, AdvancerMan requested changes

2022-07-26 13:23 UTC, AdvancerMan commented on .github/workflows/balancer_build_from_fork.yml
> +ame: "[Balancer] build image from fork"
from fork скорее неправильно. Лучше просто "build docker image"

2022-07-26 13:23 UTC, AdvancerMan commented on .github/workflows/balancer_build_from_fork.yml
> +ame: "[Balancer] build image from fork"
В смысле pr может быть необязатеольно из форка

2022-07-26 13:23 UTC, AdvancerMan commented on .github/workflows/balancer_build_from_fork.yml
> +      - name: build from fork
from fork тоже не нужен

2022-07-26 13:23 UTC, AdvancerMan commented on .github/workflows/service_build_from_fork.yml
> +          git submodule update
это можно сделать в actions/checkout

2022-07-26 13:23 UTC, AdvancerMan commented on .github/workflows/service_build_from_fork.yml
> +          git submodule update
Вроде recursive: true, что то такое

2022-07-26 13:23 UTC, AdvancerMan commented on .github/workflows/service_build_from_fork.yml
> +          git submodule update
```
      - uses: actions/checkout@v2
        with:
          submodules: recursive
```

2022-07-26 16:01 UTC, AndyForWork commented
https://github.com/SkoltechSummerCamp/5Gst/issues/9

2022-07-27 13:47 UTC, AndyForWork commented
https://github.com/SkoltechSummerCamp/5Gst/issues/54

2022-07-27 15:39 UTC, closed without merging